---

- src: https://github.com/h4rdL1nk/ansible-role-docker
  scm: git
  version: community-edition
  name: ansible-role-docker-ce

- src: https://github.com/luismiguelsaez/ansible-role-jenkins-server.git
  scm: git
  version: master
