---

- name: Docker bootstrap ( overlay storage driver )
  gather_facts: True
  hosts: all
  become: True

  roles:

    - role: ansible-role-docker-ce
      docker_ce_enable: True
      docker_ce_so_packages:
        - lvm2
      docker_lvm_storage_enable: True
      docker_lvm_storage_pv_devices: /dev/sdb
      docker_daemon_config:
        bip: "192.168.200.1/24"
        exec-opts:
          - native.cgroupdriver=systemd 
        hosts:
          - unix:///var/run/docker.sock
        live-restore: true
        storage-driver: overlay2
        icc: true
        selinux-enabled: true
        userland-proxy: true
        log-level: info
